version: '3.9'
services:
  evolution-api:
    container_name: ${EVOLUTION_API_CONTAINER_NAME}
    image: atendai/evolution-api:${EVOLUTION_API_IMAGE_TAG}
    restart: always
    ports:
      - "${EVOLUTION_API_HOST_PORT}:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
volumes:
  evolution_instances:
